{% set version = "5.3.0" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: 4e109ca30d1edec1ac60cdbe341905dc3b8f55b16855e03a54aaf59e51ec8c6f

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    # pkg-config is needed to locate %PREFIX%\Library\include\libxml2 on Windows.
    - pkg-config  # [win]
  host:
    - python
    - cython >=3.0.11
    - libxml2 2.13.5
    - libxslt {{ libxslt }}
    - pip
    - setuptools
    - wheel
    - libiconv  # [win]
    - zlib      # [win]
  run:
    - python
    - libxml2 # has run exports
    - libxslt # has run exports

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
    - lxml.includes
    - lxml.html
    - lxml.isoschematron
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://lxml.de/
  license: BSD-3-Clause and GPL-2.0-only and ZPL-2.0 and LicenseRef-ElementTree
  license_family: Other
  license_file: LICENSES.txt
  summary: Pythonic binding for the C libraries libxml2 and libxslt.
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: https://lxml.de/index.html#documentation
  dev_url: https://github.com/lxml/lxml

extra:
  recipe-maintainers:
    - jjhelmus
    - ocefpaf
