{% set version = "4.2.0" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: 7d96fbb5f23a62300aa9bef7d286cd61aca8902357619c8708c0290aba5df73f

build:
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed . --global-option="--with-xslt-config=$PREFIX/bin/xslt-config"  # [not win]
    - python -m pip install --no-deps --ignore-installed .  # [win]

requirements:
  build:
    - python
    - pip
    - cython
    - libxml2 2.9.*
    - libxslt
  run:
    - python
    - libxml2 2.9.*
    - libxslt

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
  commands:
    - conda inspect linkages -p $PREFIX lxml  # [not win]
    - conda inspect objects -p $PREFIX lxml  # [osx]

about:
  home: http://lxml.de/
  license: BSD 3-Clause, GPL-2.0, ZPL-2.0, and ElementTree
  license_file: LICENSES.txt
  summary: 'Pythonic binding for the C libraries libxml2 and libxslt.'
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: 'http://lxml.de/index.html#documentation'
  dev_url: https://github.com/lxml/lxml

extra:
  recipe-maintainers:
    - jjhelmus
    - ocefpaf
