{% set version = "4.8.0" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: f63f62fc60e6228a4ca9abae28228f35e1bd3ce675013d1dfb828688d50c6e23

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29.7
    # see https://github.com/lxml/lxml/blob/master/INSTALL.txt
    - libxml2 >=2.9.2
    - libxslt
    - pip
    - setuptools
    - wheel
  run:
    - python
    - libxslt >=1.1.28

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
    - lxml.includes
    - lxml.html
    - lxml.isoschematron
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://lxml.de/
  license: BSD-3-Clause and GPL-2.0-only and ZPL-2.0 and LicenseRef-ElementTree
  license_file: LICENSES.txt
  summary: Pythonic binding for the C libraries libxml2 and libxslt.
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: https://lxml.de/index.html#documentation
  dev_url: https://github.com/lxml/lxml
  doc_source_url: https://github.com/lxml/lxml/tree/master/doc

extra:
  recipe-maintainers:
    - jjhelmus
    - ocefpaf
