{% set version = "3.7.3" %}

package:
  name: lxml
  version: {{ version }}

source:
  fn: lxml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: aa502d78a51ee7d127b4824ff96500f0181d3c7826e6ee7b800d068be79361c7

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record record.txt --with-xslt-config=$PREFIX/bin/xslt-config  # [not win]
    - python setup.py install --single-version-externally-managed --record record.txt  # [win]

requirements:
  build:
    - python
    - setuptools
    - cython
    - libxml2 2.9.*
    - libxslt
  run:
    - python
    - libxml2 2.9.*
    - libxslt

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
  commands:
    - conda inspect linkages -p $PREFIX lxml  # [not win]
    - conda inspect objects -p $PREFIX lxml  # [osx]

about:
  home: http://lxml.de/
  license: BSD 3-Clause, GPL-2.0, ZPL-2.0, and ElementTree
  license_file: LICENSES.txt
  summary: 'Pythonic binding for the C libraries libxml2 and libxslt.'
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: 'http://lxml.de/index.html#documentation'
  dev_url: https://github.com/lxml/lxml

extra:
  recipe-maintainers:
    - ocefpaf
