{% set version = "4.9.2" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: 2455cfaeb7ac70338b3257f41e21f0724f4b5b0c0e7702da67ee6c3640835b67

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython 0.29.32
    - libxml2 2.10.3
    - libxslt 1.1.35
    - pip
    - setuptools
    - wheel
  run:
    - python
    - libxml2 >=2.9.2,!=2.9.11,!=2.9.12,<2.11.0a0
    # Recommend libxslt 1.1.28 or later.
    - libxslt >=1.1.28,<2.0.0a0

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
    - lxml.includes
    - lxml.html
    - lxml.isoschematron
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://lxml.de/
  license: BSD-3-Clause and GPL-2.0-only and ZPL-2.0 and LicenseRef-ElementTree
  license_family: Other
  license_file: LICENSES.txt
  summary: Pythonic binding for the C libraries libxml2 and libxslt.
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: https://lxml.de/index.html#documentation
  dev_url: https://github.com/lxml/lxml

extra:
  recipe-maintainers:
    - jjhelmus
    - ocefpaf
