appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kQHzod03o5j87OIzR/NVjqevQMoECg6NEyOnIKX+w7qJ6KT43sZ0h74RXq39Xtk8AEHDrDB6OAKJHJkxoMXWeI5z9IgeagNxw9QkBmdVIwrJ5bMQgmg4ml/LlHZKOJaHNhg0JC8Xo2Z3H01XrIQYY7N9WVvv3rBvdp25iWN4BcCICcIHetNUYga7DzhGufUVsofaFtucUY6tMHsplD9AO4MsZutg74qXFEkPc98PBLJETojDYdtB5jqFX/vBazeUwEVzxvnoBuuXBBWfvd3I7KlxAV1PX4YWnFq53mDyA5eRkb2tTG0BXdZuRWaN8zuAYP18cSO8R98vswjaLXNZPDFy8+u71ZibBbyicQ5adRKoPai/Tw8099XzIg47mr5q5qWp2nLkpkauTs50nnORFq1KI3S/jY1JyUykQtSkxBlkCvfL+OZp/4rQvlxbgMHNYhh2mkRO7Uh2Yw3nSa2jmzRRplFKQxqG9RnMVxHv9W10IYy9SHlKZ1ffMhhpNIcdyIslz6bcOGoYjkrDcnvLa1UXUbKurKFYYodDGzSwLcdSoFN8upzoIPMaOSOKPMiLWrB3rF4VoWhAtDzvYhpuGP324nimH75HhIzq84xDtx+zfKlaikiPl2QEqXalBXAPAxWdJQ7+W+BTnwM6foopceVntSS6ty6MJbck3jW5CnE=}
