travis:
  secure:
    BINSTAR_TOKEN: nEcFbupJiBSgXtQIk4hkyVvSASTPQUY+6VywfcYiWcC8rcOc6qEMSKq79HzfbnDFcjjpePJxhsNpta/i0qYZMoECUIJg8XY7ZyR15IyeRCDxUK1shXpfdSzc7g0gwBtHGaEIdsgphD9dUEr/vzp61N8CwF7JjByawPjUrqbAzX2CPRZcJ4UAcvKHGbwfiG6s9f20NtseQ3tnJASNpzlOxeruHJUgwruyHWq/KrXiW3ulclSO9iFqN/u6BGKafitDeiKTDUMGFS1Tnt6NPmJBjL6rn7THSqwQzfcEdRLLhOWaaxR2WjMoaPX2TTvVq0ruoZJNiZbUG0aliiFUC/4QukQEkr46UxIP/VyZsqtW1MFBDcqmJzSHnywxLtRXNB7hWCBo70Y0WH1KmJrCFFvzH3ykeRP9SUft7N56LIZ5VxrPHag6kuYPJNsw2vtrljQKHIhN3tA/lvIaiDzIQKY9ObGtTJ7cc7Bj550/hh+AQvrjXlpmInMnD+2ILw6jZQ0j+/oz/K4NsBe/CleMR4isa/nDmav75gp/xpYl69nqKiZRwYxUWCH5seelfNJtHSy4p4fCdw2EzFWAyVTy75xAmfIoDPoSjyvE6qlTfcyIaCMi6T7eRZNjUExLihA3ioiYeWSaMynf/dcUjTAH+tgv5UrqL6L0A9m4isEdCA6pGjI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
